version: 0.2

phases:
  pre_build:
    commands:
      - echo installing node modules...
      - npm install
  build: 
    commands:
      - echo starting build...
      - npm start
artifacts:
  files:
    - app.js
    - package.json
    - node_modules/async/*